prev deploy

diff --git a/.github/workflows/azure_function_deploy.yml b/.github/workflows/azure_function_deploy.yml
--- a/.github/workflows/azure_function_deploy.yml
+++ b/.github/workflows/azure_function_deploy.yml
@@ -68,17 +68,23 @@ jobs:
       - name: Check requirements.txt content
         run: cat requirements.txt
 
+      - name: Verify requirements.txt existence
+        run: |
+          if [ ! -f requirements.txt ]; then echo "requirements.txt not found"; exit 1; fi
+
       - name: Resolve Project Dependencies Using Pip
         shell: bash
         run: |
-          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
           python -m pip install --upgrade pip
           pip install -r requirements.txt --target=".python_packages/lib/site-packages"
-          popd
 
       - name: List installed packages
         run: |
           python -m pip list
+
+      - name: Show directory structure
+        run: |
+          ls -R
 
       - name: Login to Azure
         uses: azure/login@v1
